### ISSUE TITLE
Server Message Feature

### ISSUE THREAD

**Issue by BLOODWOLF333** [rjhancock/mm-api#8]
![image](https://user-images.githubusercontent.com/16950832/35199527-d3bc513a-fec4-11e7-8bb1-721ff3cd2a5f.png)

If it would be possible, allow a message to be displayed for each server and set by the host.  To let other players know what the host's intentions are, "looking for a role-playing OPFOR" or "looking for a quick-game or tournament players" for example.

**Comment by rjhancock** [comment]
Done.
